apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "common.names.fullname" .) .Values.serviceAccount.name }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
