apiVersion: v2
name: reporting-init
description: A Helm chart for initializing OpenG2P Reporting connectors.
type: application
version: 1.2.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P Reporting Init"
