apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-properties
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  connect-distributed.properties: |-
    {{- range $k, $v := .Values.propertiesOverride }}
    {{ $k }}={{ include "common.tplvalues.render" (dict "value" $v "context" $) }}
    {{- end }}
