{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "os-kafka-connector.fullname" . }}
  labels:
    app: {{ template "os-kafka-connector.name" . }}
    chart: {{ template "os-kafka-connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
