# Kafka with zookeeper from bitnami charts if not preinstalled, enable these
bitnami-kafka:
  enabled: false

# Debezium kafka connector
debezium:
  enabled: true
  kafka:
    server: "kafka.kafka:9092"

# Elasticsearch kafka connector
confluentinc:
  enabled: true
  cp-kafka-connect:
    enabled: true
    kafka:
      bootstrapServers: kafka.kafka:9092
    configurationOverrides:
      zookeeper.connect: kafka-zookeeper.kafka:2181

# KafkaClient
kafkaClient:
  enabled: false

# Enable if you do not have Elastisearch already installed in your cluster
bitnami-elasticsearch:
  enabled: false
