debezium:
  enabled: true
  replicaCount: 1
  image: debezium/connect:1.7.0.Final
  imagePullPolicy: Always
  port: 8083
  fixer_container:
    image: mosipid/debezium-fixer:1.2.0.1-B2
    imagePullPolicy: Always
    startup_delay: "30s"
    probe_time_period: "30s"
    error_level1: "failed"
    error_level2: "PSQLException: An I/O error occurred while sending to the backend"
  kafka:
    server: "kafka:9092"
    groupId: "1"
    topics:
      offset: debez-connect-offsets
      config: debez-connect-configs
      status: debez-connect-status

