apiVersion: v2
name: reporting
description: A Helm chart for OpenG2P Reporting module.
type: application
version: 0.0.0-develop
appVersion: ""
dependencies:
- name: debezium-helm-chart
  alias: debezium
  repository: "https://confluentinc.github.io/cp-helm-charts/"
  version: ">= 0.6.1"
  condition: confluentinc.enabled
- name: kafka
  alias: bitnami-kafka
  repository: "https://charts.bitnami.com/bitnami"
  version: ">= 14.0.3"
  condition: bitnami-kafka.enabled
- name: os-kafka-connector
  version: 0.0.0-develop
  condition: os-kafka-connector.enabled
  icon: https://openg2p.github.io/openg2p-helm/openg2p-reporting-logo.png
  xyds: hello
  annotations:
    catalog.cattle.io/display-name: "OpenG2P Reporting"
