debezium:
  enabled: true
  replicaCount: 1
  image: debezium/connect:1.7.0.Final
  imagePullPolicy: Always
  port: 8083
  fixer_container:
    image: mosipid/debezium-fixer:1.2.0.1-B2
    imagePullPolicy: Always
    startup_delay: "30s"
    probe_time_period: "30s"
    error_level1: "failed"
    error_level2: "PSQLException: An I/O error occurred while sending to the backend"
  kafka:
    server: "kafka:9092"
    groupId: "1"
    topics:
      offset: debez-connect-offsets
      config: debez-connect-configs
      status: debez-connect-status

kafkaClient:
  enabled: true
  image: confluentinc/cp-kafka
  db_secretref:
    name: postgres-postgresql
    key: postgresql-password

bitnami-kafka:
  fullnameOverride: kafka
  enabled: true
  replicaCount: 4
  persistence:
    enabled: false
  zookeeper:
    fullnameOverride: kafka-zookeeper
    enabled: true
    replicaCount: 4
    persistence:
      enabled: false

confluentinc:
  enabled: true

  cp-zookeeper:
    enabled: false
  cp-kafka:
    enabled: false
  cp-kafka-rest:
    enabled: false
  cp-schema-registry:
    enabled: false
  cp-ksql-server:
    enabled: false
  cp-control-center:
    enabled: false

  os-kafka-connector:
    enabled: true
    replicaCount: 1
    image: openg2p/os-kafka-connector
    imageTag: develop
    imagePullPolicy: Always

    kafka:
      bootstrapServers: kafka:9092

    prometheus:
      jmx:
        enabled: false

    configurationOverrides:
      config.storage.replication.factor: "1"
      key.converter.schemas.enable: "false"
      offset.storage.replication.factor: "1"
      plugin.path: /opt/kafka/connectors
      replication.factor: "1"
      status.storage.replication.factor: "1"
      value.converter.schemas.enable: "false"
      zookeeper.connect: zookeeper:2181
    customEnv: {}

os-kafka-connector:
  enabled: true
  global:
    kibanaEnabled: true
  data:
    fullnameOverride: os-kafka-connector-data
    heapSize: 728m
    persistence:
      enabled: false

  master:
    fullnameOverride: os-kafka-connector-master
    heapSize: 1024m
    persistence:
      enabled: false

  coordinating:
    fullnameOverride: opensearch-coordinating-only
  kibana:
    fullnameOverride: kibana
    persistence:
      enabled: false
